# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['tugboat.py']
APP_NAME = "Tugboat"
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
    'iconfile': 'tugboat_icon.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Put your stuff into JAMF",
        'CFBundleIdentifier': "edu.utah.scl.tugboat",
        'CFBundleVersion': "1.5.4",
        'CFBundleShortVersionString': "1.5.4",
        'NSHumanReadableCopyright': u"Copyright © 2018, University of Utah, All Rights Reserved"
    }

}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
